'use strict';
module.exports = `

{
    "results": [
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "kind",
                            0.08,
                            0.37
                        ],
                        [
                            "of",
                            0.37,
                            0.48
                        ],
                        [
                            "rebel",
                            0.48,
                            0.99
                        ],
                        [
                            "guy",
                            1.04,
                            1.4
                        ]
                    ],
                    "confidence": 0.46,
                    "transcript": "kind of rebel guy "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "you",
                            2.27,
                            2.36
                        ],
                        [
                            "know",
                            2.36,
                            2.53
                        ],
                        [
                            "is",
                            2.53,
                            2.66
                        ],
                        [
                            "in",
                            2.66,
                            2.75
                        ],
                        [
                            "the",
                            2.75,
                            2.82
                        ],
                        [
                            "military",
                            2.82,
                            3.28
                        ],
                        [
                            "ex",
                            3.28,
                            3.5
                        ],
                        [
                            "military",
                            3.5,
                            4.24
                        ],
                        [
                            "who",
                            4.24,
                            4.34
                        ],
                        [
                            "start",
                            4.34,
                            4.68
                        ],
                        [
                            "a",
                            4.68,
                            4.75
                        ],
                        [
                            "rock",
                            4.75,
                            5.1
                        ],
                        [
                            "band",
                            5.13,
                            5.58
                        ],
                        [
                            "called",
                            5.58,
                            5.81
                        ],
                        [
                            "samurai",
                            5.81,
                            6.97
                        ],
                        [
                            "protest",
                            7.55,
                            8.2
                        ],
                        [
                            "music",
                            8.2,
                            8.91
                        ],
                        [
                            "so",
                            9.26,
                            9.51
                        ],
                        [
                            "it's",
                            9.51,
                            9.61
                        ],
                        [
                            "like",
                            9.61,
                            9.81
                        ],
                        [
                            "for",
                            9.81,
                            10.25
                        ]
                    ],
                    "confidence": 0.69,
                    "transcript": "you know is in the military ex military who start a rock band called samurai protest music so it's like for "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "I",
                            37.62,
                            37.66
                        ],
                        [
                            "met",
                            37.66,
                            37.89
                        ],
                        [
                            "with",
                            37.89,
                            38.1
                        ],
                        [
                            "city",
                            38.1,
                            38.39
                        ],
                        [
                            "project",
                            38.39,
                            38.92
                        ],
                        [
                            "read",
                            38.92,
                            39.29
                        ],
                        [
                            "in",
                            39.29,
                            39.43
                        ],
                        [
                            "July",
                            39.43,
                            40.01
                        ],
                        [
                            "of",
                            40.01,
                            40.15
                        ],
                        [
                            "last",
                            40.15,
                            40.6
                        ],
                        [
                            "year",
                            40.6,
                            41.03
                        ],
                        [
                            "twenty",
                            41.36,
                            41.7
                        ],
                        [
                            "eighteen",
                            41.7,
                            42.25
                        ]
                    ],
                    "confidence": 0.86,
                    "transcript": "I met with city project read in July of last year 2018 "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "Los",
                            43.55,
                            43.85
                        ],
                        [
                            "Angeles",
                            43.85,
                            44.56
                        ],
                        [
                            "the",
                            45.08,
                            45.39
                        ]
                    ],
                    "confidence": 0.83,
                    "transcript": "Los Angeles the "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "%HESITATION",
                            46.94,
                            47.22
                        ],
                        [
                            "short",
                            47.61,
                            47.91
                        ],
                        [
                            "demo",
                            47.99,
                            48.57
                        ],
                        [
                            "and",
                            48.6,
                            49.16
                        ],
                        [
                            "introduced",
                            49.59,
                            50.07
                        ],
                        [
                            "me",
                            50.07,
                            50.22
                        ],
                        [
                            "to",
                            50.22,
                            50.36
                        ],
                        [
                            "the",
                            50.36,
                            50.49
                        ],
                        [
                            "idea",
                            50.49,
                            51.07
                        ],
                        [
                            "of",
                            51.1,
                            51.51
                        ]
                    ],
                    "confidence": 0.84,
                    "transcript": "short demo and introduced me to the idea of "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "the",
                            52.51,
                            52.61
                        ],
                        [
                            "character",
                            52.61,
                            53.12
                        ],
                        [
                            "Johnny",
                            53.12,
                            53.58
                        ],
                        [
                            "silver",
                            53.58,
                            54.19
                        ],
                        [
                            "and",
                            54.95,
                            55.45
                        ],
                        [
                            "so",
                            55.45,
                            55.58
                        ],
                        [
                            "they",
                            55.58,
                            55.68
                        ],
                        [
                            "walked",
                            55.68,
                            55.94
                        ],
                        [
                            "me",
                            55.94,
                            56.04
                        ],
                        [
                            "through",
                            56.04,
                            56.42
                        ],
                        [
                            "the",
                            56.94,
                            57.07
                        ],
                        [
                            "concept",
                            57.07,
                            57.71
                        ],
                        [
                            "of",
                            57.71,
                            57.78
                        ],
                        [
                            "the",
                            57.78,
                            57.89
                        ],
                        [
                            "game",
                            57.89,
                            58.33
                        ],
                        [
                            "and",
                            58.33,
                            58.47
                        ],
                        [
                            "some",
                            58.47,
                            58.68
                        ],
                        [
                            "of",
                            58.68,
                            58.76
                        ],
                        [
                            "the",
                            58.76,
                            58.86
                        ],
                        [
                            "elements",
                            58.86,
                            59.53
                        ],
                        [
                            "and",
                            59.56,
                            60.07
                        ],
                        [
                            "biography",
                            60.72,
                            61.47
                        ],
                        [
                            "of",
                            61.47,
                            61.56
                        ],
                        [
                            "your",
                            61.56,
                            61.65
                        ],
                        [
                            "character",
                            61.65,
                            62.34
                        ],
                        [
                            "and",
                            62.68,
                            63.24
                        ],
                        [
                            "%HESITATION",
                            63.24,
                            63.54
                        ],
                        [
                            "sounded",
                            64.04,
                            64.4
                        ],
                        [
                            "great",
                            64.4,
                            64.68
                        ],
                        [
                            "to",
                            64.68,
                            64.79
                        ],
                        [
                            "me",
                            64.79,
                            65.04
                        ]
                    ],
                    "confidence": 0.87,
                    "transcript": "the character Johnny silver and so they walked me through the concept of the game and some of the elements and biography of your character and sounded great to me "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "Johnny",
                            69.8,
                            70.25
                        ],
                        [
                            "silver",
                            70.25,
                            70.85
                        ],
                        [
                            "hand",
                            70.85,
                            71.22
                        ],
                        [
                            "more",
                            71.44,
                            71.87
                        ],
                        [
                            "experts",
                            71.9,
                            72.48
                        ],
                        [
                            "at",
                            73.26,
                            73.39
                        ],
                        [
                            "the",
                            73.39,
                            73.49
                        ],
                        [
                            "original",
                            73.49,
                            74.03
                        ],
                        [
                            "time",
                            74.03,
                            74.4
                        ],
                        [
                            "I",
                            74.4,
                            74.46
                        ],
                        [
                            "read",
                            74.46,
                            74.65
                        ],
                        [
                            "a",
                            74.65,
                            74.71
                        ],
                        [
                            "little",
                            74.71,
                            75.05
                        ],
                        [
                            "bit",
                            75.05,
                            75.24
                        ],
                        [
                            "but",
                            75.24,
                            75.39
                        ],
                        [
                            "for",
                            75.39,
                            75.61
                        ],
                        [
                            "them",
                            75.61,
                            75.98
                        ],
                        [
                            "the",
                            76.14,
                            76.37
                        ],
                        [
                            "war",
                            76.37,
                            76.9
                        ],
                        [
                            "they",
                            77.37,
                            77.51
                        ],
                        [
                            "were",
                            77.51,
                            77.68
                        ],
                        [
                            "like",
                            77.68,
                            78.21
                        ],
                        [
                            "be",
                            78.25,
                            78.42
                        ],
                        [
                            "here",
                            78.42,
                            78.67
                        ],
                        [
                            "now",
                            78.67,
                            79.1
                        ],
                        [
                            "this",
                            79.36,
                            79.52
                        ],
                        [
                            "is",
                            79.52,
                            79.65
                        ],
                        [
                            "what",
                            79.65,
                            79.85
                        ],
                        [
                            "we're",
                            79.85,
                            79.99
                        ],
                        [
                            "doing",
                            79.99,
                            80.4
                        ],
                        [
                            "so",
                            80.89,
                            81.37
                        ]
                    ],
                    "confidence": 0.75,
                    "transcript": "Johnny silver hand more experts at the original time I read a little bit but for them the war they were like be here now this is what we're doing so "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "maybe",
                            82.28,
                            82.58
                        ],
                        [
                            "I",
                            82.58,
                            82.67
                        ],
                        [
                            "need",
                            82.67,
                            82.85
                        ],
                        [
                            "to",
                            82.85,
                            82.92
                        ],
                        [
                            "brush",
                            82.92,
                            83.27
                        ],
                        [
                            "up",
                            83.27,
                            83.44
                        ],
                        [
                            "on",
                            83.44,
                            83.61
                        ],
                        [
                            "that",
                            83.61,
                            83.82
                        ],
                        [
                            "but",
                            83.82,
                            83.96
                        ],
                        [
                            "I",
                            83.96,
                            84.06
                        ],
                        [
                            "don't",
                            84.09,
                            84.34
                        ],
                        [
                            "know",
                            84.34,
                            84.45
                        ],
                        [
                            "how",
                            84.45,
                            84.6
                        ],
                        [
                            "much",
                            84.6,
                            84.87
                        ],
                        [
                            "I'm",
                            84.87,
                            85.01
                        ],
                        [
                            "at",
                            85.01,
                            85.16
                        ],
                        [
                            "liberty",
                            85.16,
                            85.61
                        ],
                        [
                            "to",
                            85.61,
                            85.73
                        ],
                        [
                            "say",
                            85.73,
                            86.44
                        ]
                    ],
                    "confidence": 0.86,
                    "transcript": "maybe I need to brush up on that but I don't know how much I'm at liberty to say "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "it's",
                            87.4,
                            87.6
                        ],
                        [
                            "okay",
                            87.6,
                            88.12
                        ],
                        [
                            "to",
                            88.12,
                            88.23
                        ],
                        [
                            "say",
                            88.23,
                            88.52
                        ],
                        [
                            "that",
                            88.52,
                            88.72
                        ],
                        [
                            "there",
                            88.93,
                            89.13
                        ],
                        [
                            "was",
                            89.13,
                            89.34
                        ],
                        [
                            "a",
                            89.34,
                            89.42
                        ],
                        [
                            "moment",
                            89.42,
                            90.28
                        ],
                        [
                            "of",
                            90.28,
                            90.43
                        ],
                        [
                            "may",
                            90.54,
                            90.9
                        ],
                        [
                            "be",
                            90.9,
                            91.14
                        ]
                    ],
                    "confidence": 0.87,
                    "transcript": "it's okay to say that there was a moment of may be "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "%HESITATION",
                            93.71,
                            94.26
                        ],
                        [
                            "and",
                            94.73,
                            95.41
                        ]
                    ],
                    "confidence": 0.95,
                    "transcript": "and "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "but",
                            96.43,
                            96.6
                        ],
                        [
                            "I'm",
                            96.6,
                            96.75
                        ],
                        [
                            "still",
                            96.75,
                            97.06
                        ],
                        [
                            "around",
                            97.06,
                            97.63
                        ]
                    ],
                    "confidence": 0.79,
                    "transcript": "but I'm still around "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "they're",
                            103.4,
                            103.53
                        ],
                        [
                            "letting",
                            103.53,
                            103.75
                        ],
                        [
                            "me",
                            103.75,
                            103.86
                        ],
                        [
                            "collaborate",
                            103.86,
                            104.58
                        ],
                        [
                            "a",
                            104.58,
                            104.63
                        ],
                        [
                            "little",
                            104.63,
                            104.9
                        ],
                        [
                            "bit",
                            104.9,
                            105.19
                        ],
                        [
                            "just",
                            105.8,
                            106.06
                        ],
                        [
                            "to",
                            106.06,
                            106.14
                        ],
                        [
                            "tone",
                            106.14,
                            106.65
                        ],
                        [
                            "in",
                            106.65,
                            106.86
                        ],
                        [
                            "our",
                            107.14,
                            107.32
                        ],
                        [
                            "your",
                            107.32,
                            107.6
                        ],
                        [
                            "version",
                            107.6,
                            108.15
                        ],
                        [
                            "Johnny",
                            108.15,
                            108.53
                        ],
                        [
                            "say",
                            108.53,
                            108.81
                        ],
                        [
                            "it",
                            108.81,
                            109.05
                        ],
                        [
                            "you",
                            109.08,
                            109.21
                        ],
                        [
                            "know",
                            109.21,
                            109.48
                        ]
                    ],
                    "confidence": 0.65,
                    "transcript": "they're letting me collaborate a little bit just to tone in our your version Johnny say it you know "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "and",
                            110.3,
                            110.54
                        ],
                        [
                            "moves",
                            110.54,
                            111.04
                        ],
                        [
                            "or",
                            111.04,
                            111.19
                        ],
                        [
                            "going",
                            111.19,
                            111.46
                        ],
                        [
                            "to",
                            111.46,
                            111.62
                        ],
                        [
                            "a",
                            111.62,
                            111.65
                        ],
                        [
                            "home",
                            111.65,
                            111.89
                        ],
                        [
                            "%HESITATION",
                            111.89,
                            112.0
                        ],
                        [
                            "cap",
                            112.0,
                            112.37
                        ],
                        [
                            "was",
                            112.65,
                            112.81
                        ],
                        [
                            "really",
                            112.81,
                            113.05
                        ],
                        [
                            "great",
                            113.05,
                            113.36
                        ],
                        [
                            "to",
                            113.36,
                            113.74
                        ],
                        [
                            "to",
                            113.93,
                            114.09
                        ],
                        [
                            "be",
                            114.09,
                            114.22
                        ],
                        [
                            "able",
                            114.22,
                            114.44
                        ],
                        [
                            "to",
                            114.9,
                            115.03
                        ],
                        [
                            "the",
                            115.03,
                            115.27
                        ],
                        [
                            "physical",
                            115.68,
                            116.31
                        ],
                        [
                            "embodiment",
                            116.31,
                            117.1
                        ],
                        [
                            "of",
                            117.1,
                            117.17
                        ],
                        [
                            "the",
                            117.17,
                            117.24
                        ],
                        [
                            "character",
                            117.24,
                            117.96
                        ],
                        [
                            "you",
                            118.46,
                            118.57
                        ],
                        [
                            "know",
                            118.57,
                            118.69
                        ],
                        [
                            "it",
                            118.69,
                            118.79
                        ],
                        [
                            "really",
                            118.79,
                            119.05
                        ],
                        [
                            "personalizes",
                            119.05,
                            120.04
                        ]
                    ],
                    "confidence": 0.78,
                    "transcript": "and moves or going to a home cap was really great to to be able to the physical embodiment of the character you know it really personalizes "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "in",
                            121.01,
                            121.12
                        ],
                        [
                            "this",
                            121.12,
                            121.24
                        ],
                        [
                            "part",
                            121.24,
                            121.49
                        ],
                        [
                            "of",
                            121.49,
                            121.6
                        ],
                        [
                            "the",
                            121.6,
                            121.79
                        ]
                    ],
                    "confidence": 0.77,
                    "transcript": "in this part of the "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "action",
                            122.66,
                            122.93
                        ],
                        [
                            "for",
                            122.93,
                            123.09
                        ],
                        [
                            "me",
                            123.09,
                            123.26
                        ],
                        [
                            "was",
                            123.26,
                            123.45
                        ],
                        [
                            "that",
                            123.45,
                            123.61
                        ],
                        [
                            "I",
                            123.61,
                            123.65
                        ],
                        [
                            "was",
                            123.65,
                            123.8
                        ],
                        [
                            "actually",
                            123.8,
                            124.29
                        ]
                    ],
                    "confidence": 0.87,
                    "transcript": "action for me was that I was actually "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "my",
                            125.19,
                            125.33
                        ],
                        [
                            "face",
                            125.33,
                            125.95
                        ],
                        [
                            "but",
                            125.95,
                            126.16
                        ],
                        [
                            "you",
                            126.22,
                            126.33
                        ],
                        [
                            "know",
                            126.33,
                            126.57
                        ]
                    ],
                    "confidence": 0.8,
                    "transcript": "my face but you know "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "they",
                            127.52,
                            127.65
                        ],
                        [
                            "were",
                            127.65,
                            127.74
                        ],
                        [
                            "asked",
                            127.74,
                            127.98
                        ],
                        [
                            "me",
                            127.98,
                            128.06
                        ],
                        [
                            "to",
                            128.06,
                            128.15
                        ],
                        [
                            "perform",
                            128.15,
                            128.55
                        ],
                        [
                            "the",
                            128.55,
                            128.63
                        ],
                        [
                            "role",
                            128.63,
                            129.06
                        ]
                    ],
                    "confidence": 0.6,
                    "transcript": "they were asked me to perform the role "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "cool",
                            130.31,
                            130.71
                        ],
                        [
                            "so",
                            130.9,
                            131.36
                        ]
                    ],
                    "confidence": 0.81,
                    "transcript": "cool so "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "I",
                            132.2,
                            132.23
                        ],
                        [
                            "love",
                            132.23,
                            132.47
                        ],
                        [
                            "the",
                            132.47,
                            132.56
                        ],
                        [
                            "format",
                            132.56,
                            133.1
                        ],
                        [
                            "of",
                            133.1,
                            133.19
                        ],
                        [
                            "the",
                            133.19,
                            133.31
                        ],
                        [
                            "game",
                            133.31,
                            133.69
                        ],
                        [
                            "and",
                            133.69,
                            133.91
                        ],
                        [
                            "and",
                            134.26,
                            134.4
                        ],
                        [
                            "similar",
                            134.4,
                            134.64
                        ],
                        [
                            "questions",
                            134.64,
                            135.35
                        ],
                        [
                            "ask",
                            135.35,
                            135.97
                        ],
                        [
                            "stand",
                            135.97,
                            136.58
                        ]
                    ],
                    "confidence": 0.71,
                    "transcript": "I love the format of the game and and similar questions ask stand "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "%HESITATION",
                            137.26,
                            137.78
                        ],
                        [
                            "what's",
                            138.04,
                            138.29
                        ],
                        [
                            "revealed",
                            138.29,
                            138.92
                        ],
                        [
                            "what",
                            138.92,
                            139.07
                        ],
                        [
                            "it",
                            139.07,
                            139.15
                        ],
                        [
                            "demands",
                            139.15,
                            139.65
                        ],
                        [
                            "of",
                            139.65,
                            139.73
                        ],
                        [
                            "the",
                            139.73,
                            139.86
                        ],
                        [
                            "player",
                            139.86,
                            140.44
                        ],
                        [
                            "%HESITATION",
                            141.09,
                            141.48
                        ],
                        [
                            "there's",
                            141.6,
                            141.79
                        ],
                        [
                            "some",
                            141.79,
                            141.91
                        ],
                        [
                            "interesting",
                            141.91,
                            142.34
                        ],
                        [
                            "choices",
                            142.34,
                            143.0
                        ]
                    ],
                    "confidence": 0.82,
                    "transcript": "what's revealed what it demands of the player there's some interesting choices "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "the",
                            151.35,
                            151.45
                        ],
                        [
                            "technology",
                            151.45,
                            152.22
                        ],
                        [
                            "motion",
                            152.22,
                            152.59
                        ],
                        [
                            "captures",
                            152.59,
                            153.11
                        ],
                        [
                            "got",
                            153.11,
                            153.31
                        ],
                        [
                            "a",
                            153.31,
                            153.36
                        ],
                        [
                            "little",
                            153.36,
                            153.52
                        ],
                        [
                            "quicker",
                            153.52,
                            154.0
                        ],
                        [
                            "it's",
                            154.0,
                            154.27
                        ],
                        [
                            "a",
                            154.27,
                            154.33
                        ],
                        [
                            "little",
                            154.33,
                            154.57
                        ],
                        [
                            "more",
                            154.57,
                            154.71
                        ],
                        [
                            "you",
                            154.98,
                            155.05
                        ],
                        [
                            "know",
                            155.05,
                            155.14
                        ],
                        [
                            "sometimes",
                            155.14,
                            155.64
                        ],
                        [
                            "it's",
                            155.64,
                            155.78
                        ],
                        [
                            "a",
                            155.78,
                            155.85
                        ],
                        [
                            "little",
                            155.85,
                            156.03
                        ],
                        [
                            "but",
                            156.03,
                            156.2
                        ],
                        [
                            "when",
                            156.2,
                            156.35
                        ],
                        [
                            "I",
                            156.35,
                            156.41
                        ],
                        [
                            "first",
                            156.41,
                            156.81
                        ],
                        [
                            "did",
                            156.81,
                            157.01
                        ],
                        [
                            "face",
                            157.01,
                            157.4
                        ],
                        [
                            "capture",
                            157.4,
                            158.03
                        ]
                    ],
                    "confidence": 0.84,
                    "transcript": "the technology motion captures got a little quicker it's a little more you know sometimes it's a little but when I first did face capture "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "I",
                            159.1,
                            159.13
                        ],
                        [
                            "think",
                            159.13,
                            159.47
                        ],
                        [
                            "it",
                            159.47,
                            159.57
                        ],
                        [
                            "was",
                            159.57,
                            159.72
                        ],
                        [
                            "like",
                            159.72,
                            159.88
                        ],
                        [
                            "an",
                            159.88,
                            159.96
                        ],
                        [
                            "array",
                            159.96,
                            160.56
                        ],
                        [
                            "of",
                            160.56,
                            160.7
                        ],
                        [
                            "cameras",
                            160.7,
                            161.66
                        ],
                        [
                            "and",
                            162.23,
                            162.42
                        ],
                        [
                            "it",
                            162.42,
                            162.5
                        ],
                        [
                            "was",
                            162.5,
                            162.66
                        ],
                        [
                            "a",
                            162.66,
                            162.8
                        ],
                        [
                            "%HESITATION",
                            162.8,
                            162.95
                        ],
                        [
                            "blacked",
                            162.95,
                            163.39
                        ],
                        [
                            "out",
                            163.39,
                            163.61
                        ],
                        [
                            "the",
                            163.64,
                            163.81
                        ],
                        [
                            "given",
                            163.81,
                            164.03
                        ],
                        [
                            "ten",
                            164.27,
                            164.71
                        ],
                        [
                            "in",
                            164.71,
                            164.9
                        ],
                        [
                            "was",
                            164.9,
                            165.08
                        ],
                        [
                            "like",
                            165.08,
                            165.27
                        ],
                        [
                            "for",
                            165.27,
                            165.71
                        ],
                        [
                            "you",
                            165.71,
                            165.78
                        ],
                        [
                            "know",
                            165.78,
                            165.86
                        ],
                        [
                            "was",
                            165.86,
                            166.06
                        ],
                        [
                            "a",
                            166.06,
                            166.21
                        ],
                        [
                            "was",
                            166.56,
                            166.69
                        ],
                        [
                            "a",
                            166.69,
                            166.74
                        ],
                        [
                            "huge",
                            166.74,
                            167.11
                        ],
                        [
                            "deal",
                            167.11,
                            167.37
                        ],
                        [
                            "that",
                            167.37,
                            167.51
                        ],
                        [
                            "they",
                            167.51,
                            167.58
                        ],
                        [
                            "were",
                            167.58,
                            167.68
                        ],
                        [
                            "five",
                            167.68,
                            168.11
                        ],
                        [
                            "terabytes",
                            168.11,
                            168.85
                        ],
                        [
                            "state",
                            168.85,
                            169.13
                        ],
                        [
                            "five",
                            169.13,
                            169.54
                        ],
                        [
                            "terabytes",
                            169.57,
                            170.26
                        ],
                        [
                            "available",
                            170.26,
                            170.83
                        ],
                        [
                            "to",
                            170.83,
                            170.98
                        ],
                        [
                            "do",
                            170.98,
                            171.14
                        ],
                        [
                            "this",
                            171.14,
                            171.35
                        ],
                        [
                            "capture",
                            171.35,
                            172.03
                        ]
                    ],
                    "confidence": 0.71,
                    "transcript": "I think it was like an array of cameras and it was a blacked out the given 10 in was like for you know was a was a huge deal that they were 5 terabytes state 5 terabytes available to do this capture "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "and",
                            172.99,
                            173.12
                        ],
                        [
                            "it",
                            173.12,
                            173.18
                        ],
                        [
                            "was",
                            173.18,
                            173.34
                        ],
                        [
                            "like",
                            173.34,
                            173.6
                        ],
                        [
                            "almost",
                            173.6,
                            174.04
                        ],
                        [
                            "like",
                            174.04,
                            174.37
                        ],
                        [
                            "a",
                            174.88,
                            174.97
                        ],
                        [
                            "like",
                            174.97,
                            175.26
                        ],
                        [
                            "some",
                            175.26,
                            175.73
                        ],
                        [
                            "like",
                            175.91,
                            176.24
                        ],
                        [
                            "black",
                            176.37,
                            176.73
                        ],
                        [
                            "on",
                            176.73,
                            176.92
                        ],
                        [
                            "black",
                            176.95,
                            177.29
                        ],
                        [
                            "ops",
                            177.29,
                            177.64
                        ],
                        [
                            "thing",
                            177.64,
                            178.09
                        ],
                        [
                            "like",
                            178.09,
                            178.38
                        ],
                        [
                            "okay",
                            178.38,
                            178.62
                        ],
                        [
                            "this",
                            178.62,
                            178.79
                        ],
                        [
                            "is",
                            178.79,
                            178.89
                        ],
                        [
                            "super",
                            178.89,
                            179.3
                        ],
                        [
                            "secret",
                            179.3,
                            179.77
                        ],
                        [
                            "hardware",
                            179.77,
                            180.5
                        ],
                        [
                            "to",
                            180.5,
                            180.67
                        ],
                        [
                            "a",
                            180.67,
                            180.82
                        ],
                        [
                            "super",
                            180.82,
                            181.16
                        ],
                        [
                            "secret",
                            181.16,
                            181.72
                        ],
                        [
                            "tax",
                            181.82,
                            182.16
                        ],
                        [
                            "stuff",
                            182.16,
                            182.6
                        ],
                        [
                            "and",
                            182.6,
                            182.77
                        ],
                        [
                            "it",
                            182.77,
                            182.85
                        ],
                        [
                            "probably",
                            182.85,
                            183.29
                        ],
                        [
                            "was",
                            183.29,
                            183.88
                        ]
                    ],
                    "confidence": 0.79,
                    "transcript": "and it was like almost like a like some like black on black ops thing like okay this is super secret hardware to a super secret tax stuff and it probably was "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "right",
                            184.77,
                            185.09
                        ],
                        [
                            "we",
                            185.09,
                            185.2
                        ],
                        [
                            "don't",
                            185.2,
                            185.43
                        ],
                        [
                            "really",
                            185.43,
                            185.65
                        ],
                        [
                            "know",
                            185.65,
                            185.9
                        ],
                        [
                            "how",
                            185.9,
                            186.13
                        ],
                        [
                            "long",
                            186.13,
                            186.47
                        ],
                        [
                            "siege",
                            186.99,
                            187.51
                        ],
                        [
                            "anyway",
                            188.06,
                            188.36
                        ],
                        [
                            "%HESITATION",
                            188.81,
                            189.69
                        ],
                        [
                            "what",
                            190.06,
                            190.23
                        ],
                        [
                            "we",
                            190.23,
                            190.31
                        ],
                        [
                            "support",
                            190.31,
                            190.64
                        ],
                        [
                            "I",
                            190.64,
                            190.69
                        ],
                        [
                            "got",
                            190.69,
                            190.88
                        ],
                        [
                            "off",
                            190.88,
                            191.01
                        ],
                        [
                            "track",
                            191.01,
                            191.45
                        ],
                        [
                            "every",
                            191.58,
                            191.98
                        ],
                        [
                            "global",
                            191.98,
                            192.43
                        ],
                        [
                            "companies",
                            192.43,
                            193.0
                        ],
                        [
                            "city",
                            193.0,
                            193.35
                        ],
                        [
                            "is",
                            193.35,
                            193.47
                        ],
                        [
                            "going",
                            193.47,
                            193.64
                        ],
                        [
                            "to",
                            193.64,
                            193.71
                        ],
                        [
                            "be",
                            193.71,
                            193.86
                        ],
                        [
                            "blasted",
                            193.86,
                            194.49
                        ],
                        [
                            "down",
                            194.49,
                            194.77
                        ],
                        [
                            "these",
                            194.77,
                            195.0
                        ],
                        [
                            "doors",
                            195.0,
                            195.46
                        ],
                        [
                            "do",
                            195.87,
                            195.98
                        ],
                        [
                            "would",
                            195.98,
                            196.17
                        ],
                        [
                            "you",
                            196.17,
                            196.6
                        ],
                        [
                            "any",
                            196.68,
                            196.9
                        ],
                        [
                            "US",
                            196.9,
                            197.09
                        ],
                        [
                            "cycle",
                            197.09,
                            197.64
                        ]
                    ],
                    "confidence": 0.75,
                    "transcript": "right we don't really know how long siege anyway what we support I got off track every global companies city is going to be blasted down these doors do would you any US cycle "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "a",
                            198.81,
                            198.87
                        ],
                        [
                            "couple",
                            198.87,
                            199.2
                        ],
                        [
                            "people",
                            199.2,
                            199.46
                        ],
                        [
                            "that",
                            199.46,
                            199.6
                        ],
                        [
                            "I've",
                            199.6,
                            199.76
                        ],
                        [
                            "worked",
                            199.76,
                            200.18
                        ],
                        [
                            "with",
                            200.18,
                            200.39
                        ],
                        [
                            "who's",
                            200.39,
                            200.67
                        ],
                        [
                            "done",
                            200.67,
                            200.98
                        ],
                        [
                            "voices",
                            200.98,
                            201.59
                        ],
                        [
                            "in",
                            201.59,
                            201.76
                        ],
                        [
                            "games",
                            201.76,
                            202.47
                        ],
                        [
                            "%HESITATION",
                            202.68,
                            203.37
                        ]
                    ],
                    "confidence": 0.88,
                    "transcript": "a couple people that I've worked with who's done voices in games "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "and",
                            204.26,
                            204.97
                        ],
                        [
                            "I",
                            205.58,
                            205.72
                        ],
                        [
                            "hadn't",
                            205.72,
                            206.12
                        ],
                        [
                            "done",
                            206.12,
                            206.37
                        ],
                        [
                            "that",
                            206.37,
                            206.6
                        ],
                        [
                            "yet",
                            206.6,
                            207.0
                        ],
                        [
                            "for",
                            207.0,
                            207.18
                        ],
                        [
                            "me",
                            207.18,
                            207.44
                        ],
                        [
                            "I",
                            207.44,
                            207.52
                        ],
                        [
                            "was",
                            207.52,
                            207.71
                        ],
                        [
                            "attracted",
                            207.71,
                            208.21
                        ],
                        [
                            "to",
                            208.21,
                            208.34
                        ],
                        [
                            "the",
                            208.34,
                            208.54
                        ],
                        [
                            "storytelling",
                            208.54,
                            209.35
                        ],
                        [
                            "different",
                            209.59,
                            210.0
                        ],
                        [
                            "versions",
                            210.0,
                            210.94
                        ],
                        [
                            "you",
                            211.07,
                            211.17
                        ],
                        [
                            "know",
                            211.17,
                            211.41
                        ]
                    ],
                    "confidence": 0.82,
                    "transcript": "and I hadn't done that yet for me I was attracted to the storytelling different versions you know "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "not",
                            212.58,
                            212.82
                        ],
                        [
                            "just",
                            212.82,
                            213.01
                        ],
                        [
                            "use",
                            213.01,
                            213.22
                        ],
                        [
                            "your",
                            213.22,
                            213.37
                        ],
                        [
                            "own",
                            213.37,
                            213.51
                        ],
                        [
                            "and",
                            213.51,
                            213.7
                        ],
                        [
                            "choose",
                            213.8,
                            214.14
                        ],
                        [
                            "your",
                            214.14,
                            214.32
                        ],
                        [
                            "own",
                            214.32,
                            214.53
                        ],
                        [
                            "path",
                            214.59,
                            215.16
                        ],
                        [
                            "I",
                            215.87,
                            215.9
                        ],
                        [
                            "thought",
                            215.9,
                            216.17
                        ],
                        [
                            "that",
                            216.17,
                            216.39
                        ],
                        [
                            "was",
                            216.39,
                            216.78
                        ],
                        [
                            "cool",
                            216.96,
                            217.2
                        ],
                        [
                            "because",
                            217.66,
                            217.83
                        ],
                        [
                            "there's",
                            217.83,
                            218.01
                        ],
                        [
                            "so",
                            218.01,
                            218.13
                        ],
                        [
                            "many",
                            218.13,
                            218.51
                        ],
                        [
                            "multiple",
                            218.69,
                            219.16
                        ],
                        [
                            "mass",
                            219.16,
                            219.52
                        ],
                        [
                            "multi",
                            219.52,
                            219.8
                        ],
                        [
                            "player",
                            219.95,
                            220.26
                        ],
                        [
                            "games",
                            220.26,
                            220.76
                        ],
                        [
                            "we",
                            221.19,
                            221.27
                        ],
                        [
                            "always",
                            221.27,
                            221.54
                        ],
                        [
                            "knew",
                            221.54,
                            221.64
                        ],
                        [
                            "what",
                            221.64,
                            221.83
                        ],
                        [
                            "this",
                            221.83,
                            221.98
                        ],
                        [
                            "one's",
                            221.98,
                            222.16
                        ],
                        [
                            "character",
                            222.16,
                            222.59
                        ],
                        [
                            "%HESITATION",
                            222.59,
                            222.66
                        ],
                        [
                            "private",
                            222.66,
                            223.07
                        ],
                        [
                            "almost",
                            223.27,
                            223.55
                        ],
                        [
                            "cinematic",
                            223.55,
                            224.11
                        ],
                        [
                            "experience",
                            224.11,
                            225.12
                        ],
                        [
                            "even",
                            225.24,
                            225.53
                        ],
                        [
                            "reading",
                            225.53,
                            225.88
                        ],
                        [
                            "it's",
                            225.88,
                            226.04
                        ],
                        [
                            "almost",
                            226.04,
                            226.26
                        ],
                        [
                            "like",
                            226.26,
                            226.4
                        ],
                        [
                            "literature",
                            226.4,
                            227.0
                        ],
                        [
                            "right",
                            227.59,
                            227.8
                        ],
                        [
                            "thank",
                            227.83,
                            227.99
                        ],
                        [
                            "you",
                            227.99,
                            228.07
                        ],
                        [
                            "for",
                            228.07,
                            228.13
                        ],
                        [
                            "participating",
                            228.13,
                            228.97
                        ],
                        [
                            "in",
                            228.97,
                            229.21
                        ],
                        [
                            "this",
                            229.51,
                            229.69
                        ],
                        [
                            "open",
                            229.69,
                            230.08
                        ],
                        [
                            "world",
                            230.08,
                            230.43
                        ],
                        [
                            "but",
                            230.43,
                            230.55
                        ],
                        [
                            "it's",
                            230.55,
                            230.68
                        ],
                        [
                            "your",
                            230.68,
                            230.85
                        ],
                        [
                            "story",
                            230.85,
                            231.46
                        ],
                        [
                            "your",
                            231.72,
                            231.99
                        ],
                        [
                            "choice",
                            231.99,
                            232.84
                        ],
                        [
                            "my",
                            233.09,
                            233.3
                        ],
                        [
                            "character",
                            233.3,
                            233.93
                        ],
                        [
                            "Johnny",
                            233.93,
                            234.34
                        ],
                        [
                            "interacts",
                            234.34,
                            234.93
                        ],
                        [
                            "with",
                            234.93,
                            235.11
                        ],
                        [
                            "the",
                            235.35,
                            235.5
                        ],
                        [
                            "world",
                            235.5,
                            235.79
                        ]
                    ],
                    "confidence": 0.67,
                    "transcript": "not just use your own and choose your own path I thought that was cool because there's so many multiple mass multi player games we always knew what this one 's character private almost cinematic experience even reading it's almost like literature right thank you for participating in this open world but it's your story your choice my character Johnny interacts with the world "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "are",
                            237.31,
                            237.49
                        ],
                        [
                            "the",
                            237.49,
                            237.6
                        ],
                        [
                            "characters",
                            237.6,
                            238.01
                        ],
                        [
                            "to",
                            238.01,
                            238.15
                        ],
                        [
                            "be",
                            238.42,
                            238.77
                        ]
                    ],
                    "confidence": 0.73,
                    "transcript": "are the characters to be "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "%HESITATION",
                            240.07,
                            240.4
                        ],
                        [
                            "and",
                            240.4,
                            240.57
                        ],
                        [
                            "so",
                            240.57,
                            240.81
                        ],
                        [
                            "there's",
                            240.81,
                            241.15
                        ],
                        [
                            "%HESITATION",
                            241.15,
                            241.51
                        ],
                        [
                            "I",
                            241.99,
                            242.15
                        ],
                        [
                            "interact",
                            242.15,
                            242.68
                        ],
                        [
                            "with",
                            242.68,
                            242.83
                        ],
                        [
                            "whoever's",
                            243.08,
                            243.48
                        ],
                        [
                            "playing",
                            243.48,
                            243.94
                        ]
                    ],
                    "confidence": 0.72,
                    "transcript": "and so there's I interact with whoever's playing "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "and",
                            245.25,
                            245.47
                        ],
                        [
                            "I'm",
                            245.47,
                            245.59
                        ],
                        [
                            "part",
                            245.59,
                            245.89
                        ],
                        [
                            "of",
                            245.89,
                            245.97
                        ],
                        [
                            "their",
                            245.97,
                            246.14
                        ],
                        [
                            "journey",
                            246.14,
                            246.7
                        ]
                    ],
                    "confidence": 0.64,
                    "transcript": "and I'm part of their journey "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "and",
                            248.29,
                            248.76
                        ],
                        [
                            "%HESITATION",
                            248.76,
                            249.09
                        ],
                        [
                            "they're",
                            249.7,
                            249.9
                        ],
                        [
                            "also",
                            249.9,
                            250.26
                        ],
                        [
                            "part",
                            250.26,
                            250.62
                        ]
                    ],
                    "confidence": 0.8,
                    "transcript": "and they're also part "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "so",
                            252.1,
                            252.7
                        ]
                    ],
                    "confidence": 0.96,
                    "transcript": "so "
                }
            ],
            "final": true
        },
        {
            "alternatives": [
                {
                    "timestamps": [
                        [
                            "you",
                            253.63,
                            253.75
                        ],
                        [
                            "know",
                            253.75,
                            253.99
                        ],
                        [
                            "see",
                            254.61,
                            254.85
                        ],
                        [
                            "what",
                            254.85,
                            254.98
                        ],
                        [
                            "happens",
                            254.98,
                            255.52
                        ]
                    ],
                    "confidence": 0.52,
                    "transcript": "you know see what happens "
                }
            ],
            "final": true
        }
    ],
    "result_index": 0
}`;